project:    hello_world
version:    0.1
libraries:
    libhello:
        cflags: '-Wall -Werror -g -O2 -std=c99 -D_XOPEN_SOURCE=600'
        sources: [ 'library.c' ]

binaries:
    hello:
        sources: [ main.c extra.c ]
#FIXME:        ldflags: '-L . -rpath .'
        ldadd: '-lhello'
#        install => {
#            '$(LIBDIR)' => [ '-m 644', 'libhello.so' ],
#            '$(BINDIR)' => [ '-m 755', 'hello' ], 
#        },

check_header: [ stdlib.h, stdio.h, string.h, does-not-exist.h ]
check_symbol:
    fcntl.h: [ O_DOES_NOT_EXIST, O_RDWR ]
    pthread.h: [ pthread_exit ]
