project: makeconf
version: 0.1
extra_dist:
    - testing/Makefile

scripts:
    makeconf:
        sources: [ 'makeconf' ]
        dest: '$(BINDIR)'

data: 
  'template/*': '$(PKGDATADIR)/template'
  'makeconf.rb': '$(PKGDATADIR)/template'
          

#FIXME: Not handed correctly yet
#subdirs: [ testing ]

install:
    - install -d -m 755 -o foo -g bar $pkgincludedir
    - install -m 0755 makeconf $bindir
    - install -m 0644 configure config.inc.template $pkgincludedir
    - install -m 0644 configure config.inc.template $pkgincludedir

# Not really used, just for testing the language
#
check_header:
    - stdlib.h
    - unistd.h
    - nonexistent.h

check_symbol: 
    'unistd.h': ['STDIN_FILENO', 'STDOUT_FILENO']

# Not really used, just for testing pkgconfig
#
pkgconfig:
#    name: '$project'
    description: 'Description field'
#    version: '$version'
#    url: '$url'
    requires: ''
    conflicts: ''
    libs: ''
    libs.private: ''
    cflags: '-Wall -Werror'
