class AndroidProject < BaseProject

  def initialize(options)
    super(options)
    p 'TODO - extra android init'
  end

  # Parse ARGV options
  # Should only be called from Makeconf.parse_options()
  def parse_options(opts)
    super(opts)
    opts.separator ""
    opts.separator "Android options:"
  end

  def to_make
    write_android_mk
    write_application_mk

    mf = super
    mf.target('all').rules = [ 'ndk-build V=1 NDK_DEBUG=1 NDK_PROJECT_PATH=.' ]
    mf
  end

private

  # Create the Android.mk makefile
  def write_android_mk
    ofile = 'Android.mk'
    buf = [
      '# Automatically generated by ./configure -- do not edit',
      'LOCAL_PATH := $(call my-dir)',
      '',
    ]

    @build.each do |obj|
      next if obj.kind_of? Header
      buf.push 'include $(CLEAR_VARS)',
            '';

      id = obj.id
      id += '_static' if obj.kind_of? StaticLibrary
      id += '_shared' if obj.kind_of? SharedLibrary
      buf.push "LOCAL_MODULE    := #{id}"
      buf.push "LOCAL_SRC_FILES := " + obj.sources.join(' ')
      buf.push "LOCAL_CFLAGS    := " + obj.cflags.join(' ')
      buf.push translate_ldadd(obj.ldadd) if obj.ldadd
      buf.push ''
      case obj.class.to_s
      when 'StaticLibrary'
        buf.push 'include $(BUILD_STATIC_LIBRARY)'
      when 'SharedLibrary'
        buf.push 'include $(BUILD_SHARED_LIBRARY)'
      when 'Binary', 'Test'
        buf.push 'include $(BUILD_EXECUTABLE)'
      else
        throw "Unsuported class #{obj.class}"
      end
      buf.push ''
    end

    puts 'creating ' + ofile
    f = File.open(ofile, 'w')
    buf.each do |str|
      f.printf "#{str}\n" 
    end
    f.close
  
  end

  # Create the jni/Application.mk makefile
  def write_application_mk
    ofile = 'jni/Application.mk'
    buf = [
      '# Automatically generated by ./configure -- do not edit',
      'APP_PROJECT_PATH := .',
      'APP_BUILD_SCRIPT := $(APP_PROJECT_PATH)/Android.mk',
      'APP_PLATFORM     := android-14',
      'APP_OPTIM        := debug',
    ]

    Dir.mkdir 'jni' unless Dir.exists?('jni')
    puts 'creating ' + ofile
    f = File.open(ofile, 'w')
    buf.each do |str|
      f.printf "#{str}\n" 
    end
    f.close
  end

  # Translate LDADD flags into the corresponding Android.mk variables
  def translate_ldadd(ldadd)
     static_libs = []
     # TODO: shared libs
     ldadd.each do |item|
       if item =~ /\.a$/
          # FIXME: assumes it is built locally
          static_libs.push item.sub(/\.a$/, '_static')
       end
     end
     
     buf = ''
     buf += 'LOCAL_STATIC_LIBRARIES := ' + static_libs.join(' ') if static_libs
     buf
  end
end
